[profile.default]
src = "src"
out = "out"
libs = ["lib"]
allow_paths = ["../../node_modules"]
fs_permissions = [
    { access = "read-write", path = "./script/VaultData" },
    { access = "read", path = "./test/fixtures" },
    { access = "read-write", path = "./deployments/anvil/contracts.json" },
    { access = "read-write", path = "./script/v2/config" },
    { access = "read-write", path = "./anvil-deployment.json" },
]
via_ir = true
evm_version = "cancun"
optimizer = true
optimizer_runs = 1_000
solc = "0.8.25"
runs = 100000

[invariant]
fail_on_revert = true
